task_1
Aksonof/MyApplication pull request #1
Opened 2024-01-17 12:12 UTC by Aksonof

My profile markup - task 1

2024-01-17 19:31 UTC, 1937Carrie requested changes
Merge request was created little bit wrong. We see difference between current state and previous that was not been initial and because of this i can't comment all rows that i want because they were commited in previous commit. Better try to do pull request like [empty project] -> [finished task] so reviewers could see all changes. Anyway it was good start, keep going.

2024-01-17 19:31 UTC, 1937Carrie commented on app/src/main/java/com/example/myapplication/AuthActivity.kt
>              findViewById<com.google.android.material.textfield.TextInputEditText>(R.id.emailEditText)
Replace with [binding](https://developer.android.com/topic/libraries/view-binding)

2024-01-17 19:31 UTC, 1937Carrie commented on app/src/main/java/com/example/myapplication/AuthActivity.kt
>                  false
Looks like if email edittext firstly have error but user correct it lately, emailView.error still will be displayed

2024-01-17 19:31 UTC, 1937Carrie commented on app/src/main/java/com/example/myapplication/AuthActivity.kt
> +                    val handlerThread = HandlerThread("MyHandlerThread")
First time seeing using HandlerThread at first level. Try to simplify your code.

2024-01-17 19:31 UTC, 1937Carrie commented on app/src/main/java/com/example/myapplication/AuthActivity.kt
> +                    passView.error = "Password: 6+ chars, Aa-Zz, 0-9"
Better to extract such strings in string resources and care about translate it.

2024-01-17 19:31 UTC, 1937Carrie commented on app/src/main/java/com/example/myapplication/MainActivity.kt
>          var firstName = emailWithOutNumbers.substringBefore('@')
32th and 37th rows contain same code, namely _emailWithOutNumbers.**substringBefore**('@'). It was probably supposed String.substringAfter() in 37th row.

2024-01-17 19:31 UTC, 1937Carrie commented on app/src/main/res/layout-night/activity_auth.xml
There is no need to use redundant View and FrameLayout. You can place all the elements using constraints and biases in a ConstraintLayout, sometimes adding a GuideLine to precisely constrain your view.

2024-01-17 19:31 UTC, 1937Carrie commented on app/src/main/res/values/strings.xml
> +    <string name="Term">By clicking Register you agree to our\n Terms and Conditions</string>
Redundant "\n". String will be automatically wrapped if textview was set up correct.

2024-01-17 19:31 UTC, 1937Carrie commented on app/src/main/res/layout-night/activity_auth.xml
> +            android:layout_marginHorizontal="55dp"
I cant comment desired row so i leave comment here. In case like 142th row you can use 0dp for layout_width but you should to constraint start and end of view.

2024-01-18 21:55 UTC, yuriiromanenko commented on app/src/main/java/com/example/myapplication/AuthActivity.kt
>          setContentView(R.layout.activity_auth)
1) in "onCreate" should be only function. Decomposition please
   2) Maybe use binding?
  3)  autologin NOT implemented, fix this please

2024-01-18 21:55 UTC, yuriiromanenko commented on app/src/main/java/com/example/myapplication/AuthActivity.kt
> -        userEmail.setText(sharedPref.getString("email", ""))
export "email" to CONSTANTS?

2024-01-18 21:55 UTC, yuriiromanenko commented on app/src/main/java/com/example/myapplication/AuthActivity.kt
> -        userEmail.setText(sharedPref.getString("email", ""))
export "pass" to CONSTANTS?

2024-01-18 21:55 UTC, yuriiromanenko commented on app/src/main/java/com/example/myapplication/AuthActivity.kt
> -        userEmail.setText(sharedPref.getString("email", ""))
delay?

2024-01-18 22:19 UTC, yuriiromanenko commented on app/src/main/java/com/example/myapplication/MainActivity.kt
>              .substringBefore('.')
Check First letter UPPER Case?

2024-01-18 22:19 UTC, yuriiromanenko commented on app/src/main/res/layout/activity_auth.xml
>          app:layout_constraintEnd_toEndOf="parent"
app:layout_constraintBottom_toBottomOf=""

2024-01-18 22:19 UTC, yuriiromanenko commented on app/src/main/res/layout/activity_main.xml
>          app:layout_constraintTop_toTopOf="parent">
Відпрацювати різні стани кнопки “edit profile”.
Якимось чином можна змінити колір, розмір чи фон,
проявіть фантазію, важливо щоб ви розуміли як це робити
і які є стани.

2024-01-18 22:19 UTC, yuriiromanenko commented on app/src/main/res/layout/activity_main.xml
>              android:background="@android:color/transparent"
Please  realisation "Log OUT"

2024-01-18 22:19 UTC, yuriiromanenko commented on app/src/main/res/values-uk/strings.xml
Sort by activity

2024-02-03 13:08 UTC, 1937Carrie requested changes
I found some mistakes in files that were not commited so I will comment it here.

drawables/google_icon.xml constains only one item inside yourself and this is png image. Better export google logo as vector image (svg). When you will do this you will no need to using two files (drawables/icon.png, drawables/google_icon.xml) for one purpose.

Try to create new drawable for "edit profile" button using selector [link](https://developer.android.com/guide/topics/resources/drawable-resource#LayerList)

Conclusion: this version looks better but there are some issues that require to be corrected. Also you can ask in discord how to working with binding in simple way.

2024-02-03 13:08 UTC, 1937Carrie commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintGuide_end="365dp" />
Better get back to procent type because different devices have their own quantity of dp.

2024-02-03 13:08 UTC, 1937Carrie commented on app/src/main/java/com/example/myapplication/AuthActivity.kt
> +            startActivity(intent)
When you start new activity, specifically in this code, you will have two running activity in the same time. You can make sure of this by pressing back on MainActivity screen - you will see AuthActivity. So if you do not need activity more (in this case AuthActivity) you should finish it. Call "finish()".

2024-02-03 13:08 UTC, 1937Carrie commented on app/src/main/res/layout/activity_main.xml
It is wrong screen. You should have implented MyProfile screen that contains [Facebook, Linkedin, Instagram] group (orange icons).

2024-02-03 13:08 UTC, 1937Carrie commented on app/src/main/res/layout/activity_auth.xml
>          android:layout_width="331dp"
It is bad practice to use absolute value if they are too big (approximately more than 100 but it is abstract value). Try to use dynamical values for dimensions of view and use absolute values in margin or padding.

2024-02-03 13:08 UTC, 1937Carrie commented on app/src/main/res/layout/activity_auth.xml
This layout not match to design in figma. If need help with creating layout(design matching/constraints/dimensions etc.) request help in discord.

2024-02-03 13:08 UTC, 1937Carrie commented on app/src/main/res/layout/activity_auth.xml
>      </FrameLayout>
There is no need to use many nested layouts. You can create a good design using constraints because you are using the constraint layout as the root or parent layout. Also can request help in discord about this issue.

2024-02-03 13:08 UTC, 1937Carrie commented on app/src/main/java/com/example/myapplication/AuthActivity.kt
> +                    editor.putString("pass", pass)
First parameter in putString() function is key. You use key value in MainActivity also.  So better extract key values in constants.

2024-02-07 12:40 UTC, merged